# Generated by Django 4.1.7 on 2023-03-21 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Snake',
            fields=[
                ('name', models.CharField(max_length=200, verbose_name='Snake Name')),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('source_code', models.TextField()),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snake', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
