# Generated by Django 4.1.7 on 2023-03-24 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snake', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snake',
            name='snake_url',
            field=models.URLField(default='https://sample.battlesnake.server/', verbose_name='Hosted Battlesnake URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='snake',
            name='source_code',
            field=models.TextField(help_text='Your Battlesnake source code in Java. Refer to https://battlesnake.mcpt.jimmyliu.dev/getting_started/java.html for details'),
        ),
    ]
